### ISSUE TITLE
Subo CLI Segfaults and Panics During Bundle

### ISSUE THREAD

**Issue by appcypher** [suborbital/subo#102]
It is an amazing work you folks are doing here. I encountered an issue while following the walkthrough [here](https://www.youtube.com/watch?v=d0UT5WghFpQ). 

When I got to `subo build helloworld --docker`,  the following error shows up:

```
...
✅ DONE: helloworld was built -> /Users/.../Desktop/projects/important-api/helloworld/helloworld.wasm
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x13b1670]

goroutine 1 [running]:
github.com/suborbital/subo/subo/command.BuildCmd.func1(0xc000130780, 0xc0000ec4e0, 0x1, 0x2, 0x0, 0x0)
	/private/tmp/subo-20210905-4022-iy0t5p/subo-0.0.22/subo/command/build.go:81 +0x310
github.com/spf13/cobra.(*Command).execute(0xc000130780, 0xc0000ec4c0, 0x2, 0x2, 0xc000130780, 0xc0000ec4c0)
	/private/tmp/subo-20210905-4022-iy0t5p/subo-0.0.22/vendor/github.com/spf13/cobra/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000c0f00, 0x0, 0xffffffff, 0xc000096058)
	/private/tmp/subo-20210905-4022-iy0t5p/subo-0.0.22/vendor/github.com/spf13/cobra/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/private/tmp/subo-20210905-4022-iy0t5p/subo-0.0.22/vendor/github.com/spf13/cobra/command.go:897
main.main()
	/private/tmp/subo-20210905-4022-iy0t5p/subo-0.0.22/subo/main.go:10 +0x2a
```

No `runnables.wasm.zip` generated.

Subo CLI v0.0.22 (Installed via brew)
macOS Catalina v10.15.6

**Comment by jagger27** [comment]
It definitely shouldn't be crashing like this, and I was able to replicate this on Linux. Thank you for the report! 

Things move *very* quickly here, and that video was from earlier this year. A more up to date tutorial can be found here: https://github.com/suborbital/subo/blob/main/docs/get-started.md

Could you try running this instead (still uses Docker):

```
cd important-api
subo build .
```

**Comment by cohix** [comment]
Thanks for reporting this @appcypher.... appreciate the kind words, too :)

@jagger27 will look into fixing the crash, I'm glad you were able to get it working in the meantime. Please join the Discord if you have any feedback you'd like to give us! https://chat.suborbital.dev
