### ISSUE TITLE
Subo 'create' command still makes a directory if it fails to find a template

### ISSUE THREAD

**Issue by jagger27** [suborbital/subo#119]
Replication steps:

```
subo create runnable foobar --lang somethingnotsupported
```

Which still creates a `foobar` folder even though it failed.

**Comment by denopink** [comment]
Got it replicated on my end. I'll try my hand at the patch.

**Comment by denopink** [comment]
@jagger27 if `subo create runnable` fails, then wouldn't we want to delete the output dir all together (in this case we'll be deleting `foobar` and its contains) for any reason and not just for the current case `writeDotRunnable: somethingnotsupported is not an available language`?

**Comment by jagger27** [comment]
> @jagger27 if `subo create runnable` fails, then wouldn't we want to delete the output dir all together (in this case we'll be deleting `foobar` and its contents) for any reason and not just for the current case `writeDotRunnable: somethingnotsupported is not an available language`?

Yes that seems reasonable.
