### ISSUE TITLE
Subo ignores --version flag when in existing compute installations 

### ISSUE THREAD

**Issue by jagger27** [suborbital/subo#126]
If you have an existing Compute configuration setup: 
```
 subo compute deploy core --local
```

And you try to change the version by re-running the command in the same folder:
```
 subo compute deploy core --local --version v0.1.0-rc1
```
It seems to use the existing version.

**Comment by denopink** [comment]
@jagger27 I was thinking we could also add the option of passing in the token as an env var  (maybe expecting it as a base64 encoded secret) for infra-as-code, playbook and debugging purposes? Should I open a separate ticket for this or included as a part of this patch?

**Comment by denopink** [comment]
> @jagger27 I was thinking we could also add the option of passing in the token as an env var (maybe expecting it as a base64 encoded secret) for infra-as-code, playbook and debugging purposes? Should I open a separate ticket for this or included as a part of this patch?

Whoops, I missed `ReadEnvironmentToken`. Disregard my last comment!

**Comment by denopink** [comment]
@jagger27 the issue appears to be that `docker-compose.yml` never updates

Replication steps:

**Fails to update (docker-compose.yml stays the same)**
```console
 subo compute deploy core --local
 subo compute deploy core --local --version v0.1.0-rc1
 ```
 **Update Succeeds (docker-compose.yml reflects changes)**
```console
 subo compute deploy core --local
 cd ../ && subo compute deploy core --local --version v0.1.0-rc1
 ```
The cause of the issue appears to be ExecTmplDir and how it skips any overwrites:
https://github.com/suborbital/subo/blob/750b9c98a15b54d74effdbf91bd0baf9c800a4af/builder/template/templates.go#L118-L128

A simple fix would do the trick and I'm assuming we don't always want to overwrite files, so we add a new overWrite bool parameter to ExecTmplDir aswell:
```go
func ExecTmplDir(cwd, name, templatesPath, tmplName string, templateData interface{}, overWrite bool) error {
	...
		// check if the target path is an existing file, and skip it if so unless overWrite is True
		if _, err := os.Stat(filepath.Join(targetPath, targetRelPath)); err != nil {
			if os.IsNotExist(err) {
				// that's fine, continue
			} else {
				return errors.Wrap(err, "failed to Stat")
			}
		} else if info.IsDir() || !overWrite {
			// if the target file already exists and overWrite is false, we're going to skip the rest since we don't want to overwrite
			return nil
		}
	...
```

**Comment by cohix** [comment]
@denopink the latest version of Subo should delete the docker-compose file before writing a new one. Is this still persistent in v0.2.1?

**Comment by denopink** [comment]
@cohix I'm using subo version `v0.1.0`... let me test with `0.2.1` when I get back.

**Comment by denopink** [comment]
@cohix the bug appears to be persistent in `v0.2.1`

```console
(base) odc@mbp subo % docker container ls
CONTAINER ID   IMAGE                                 COMMAND          CREATED          STATUS          PORTS                    NAMES
fdd05dca8cc5   suborbital/scc-control-plane:v0.1.0   "controlplane"   27 minutes ago   Up 27 minutes   0.0.0.0:8081->8081/tcp   subo_scc-control-plane_1
d21ec0f03edf   suborbital/scc-builder:v0.1.0         "builder"        27 minutes ago   Up 27 minutes   0.0.0.0:8082->8082/tcp   subo_scc-builder_1
bb9912442676   suborbital/atmo:v0.4.2                "atmo"           2 hours ago      Up 55 minutes   0.0.0.0:8080->8080/tcp   subo_scc-atmo_1


(base) odc@mbp subo %  subo compute deploy core --local v0.1.0-rc1
⏩ START: preparing deployment
⏩ START: downloading templates
✅ DONE: templates downloaded
Enter your environment token: [my-token]
✅ DONE: ready to start installation
⏩ START: installing...
subo_scc-control-plane_1 is up-to-date
subo_scc-builder_1 is up-to-date
subo_scc-atmo_1 is up-to-date
ℹ️  use `docker ps` and `docker-compose logs` to check deployment status

PROXY: local tunnel to function editor started
2021/11/24 17:26:45 listen tcp :80: bind: address already in use
(base) odc@mbp subo % docker container ls                         
CONTAINER ID   IMAGE                                 COMMAND          CREATED          STATUS             PORTS                    NAMES
fdd05dca8cc5   suborbital/scc-control-plane:v0.1.0   "controlplane"   39 minutes ago   Up 39 minutes      0.0.0.0:8081->8081/tcp   subo_scc-control-plane_1
d21ec0f03edf   suborbital/scc-builder:v0.1.0         "builder"        39 minutes ago   Up 39 minutes      0.0.0.0:8082->8082/tcp   subo_scc-builder_1
bb9912442676   suborbital/atmo:v0.4.2                "atmo"           2 hours ago      Up About an hour   0.0.0.0:8080->8080/tcp   subo_scc-atmo_1
```

**Comment by jagger27** [comment]
> ```
> (base) odc@mbp subo %  subo compute deploy core --local v0.1.0-rc1
> ```

This command is missing the `--version` argument:
<pre>
subo compute deploy core --local <b>--version</b> v0.1.0-rc1
</pre>

That seems to work as intended.

**Comment by denopink** [comment]
@jagger27 whoops! My bad 😅

**Comment by jagger27** [comment]
@denopink Let us know if this becomes a problem again!
