### ISSUE TITLE
`subo compute create token [email]` sends the user in email verification loop ending w\401s

### ISSUE THREAD

**Issue by denopink** [suborbital/subo#137]
Replication steps:
`subo compute create token [email]`

Output:
```console
A verification code was sent to your email address. Enter the code to continue: [your code]
Error: failed to CreateEnvironmentToken: failed to Do: failed to Do request, received status code 401
```

**Comment by cohix** [comment]
@ospencer and @jagger27 tested this and confirmed it happens when an old or incorrect 6-digit code is entered. @denopink could that be what’s causing this?

**Comment by denopink** [comment]
@cohix Confirmed! It's working as expected. Maybe we can complement the current 401 error message with a more verbose explanation.

**Comment by denopink** [comment]
Issue resolved, thx team!
