### ISSUE TITLE
Directive variable conflicts with imported package name

### ISSUE THREAD

**Issue by javorszky** [suborbital/subo#184]
Here:
* package: https://github.com/suborbital/subo/blob/main/builder/context/buildcontext.go#L11
* variable: https://github.com/suborbital/subo/blob/main/builder/context/buildcontext.go#L72

They shouldn't have the same name. It's down to shadowing rules to figure out what you mean by `directive`, which can be confusing, and can lead to unexpected bugs.

**Comment by yashikajotwani12** [comment]
Hey @javorszky, I would like to know if there are other links for this because these are not opening, can you confirm, Thank you.
