### ISSUE TITLE
webpack: Permission denied

### ISSUE THREAD

**Issue by k33g** [suborbital/subo#214]
Hello
I created 4 runnables:
- `subo create runnable hello --lang tinygo`
- `subo create runnable hey`
- `subo create runnable hola --lang javascript`
- `subo create runnable plop --lang typescript`

I can build the tinygo and rust runnables, but I get an error (`webpack: Permission denied`) when I try to build the javascript and typescript runnables.

I use subo `v0.4.0`

**Comment by ospencer** [comment]
Thanks for the report! @k33g what operating system are you using?

**Comment by k33g** [comment]
@ospencer I'm working with Gitpod (I started from a Gitpod image, it's Ubuntu-based)
