### ISSUE TITLE
Verbose flag for easier debugging

### ISSUE THREAD

**Issue by flaki** [suborbital/subo#234]
For more detailed context on why I think this flag would be useful, check out suborbital/docs#108

As the above linked issue explains, we could do a lot more to support our users in using atmo, debugging and giving us extra feedback. I'm proposing a `-v|--verbose` flag for `subo` and particularly `subo dev` that would make all of these a lot easier by implementing two changes to how the command worked.

Running `subo dev --verbose` would launch Atmo and:

1. [ ] configure Atmo to show `debug` messages via passing in `-e=ATMO_LOG_LEVEL=debug` to docker, raising the default log level from `info`
2. [ ] display the [currently executed docker command](https://github.com/suborbital/subo/blob/020b497e92199e0a5b510669952c6dc8ead61640/subo/command/dev.go#L37) to aid both debugging and help with changing Atmo's configuration manually

I think this `--verbose` flag might even make sense for other commands, and we may find other ways to use this command to aid debugging, feedback and customizing Atmo for the local development instance, but these two relatively small changes might improve the DevEx a lot already.

> These two changes might be sufficiently self-contained that this could make a good first-time contributor issue as well, feel free to mark it as such if you agree with that assessment.

**Comment by kritikmodi** [comment]
I'll be working on this!

**Comment by kritikmodi** [comment]
We need the flag for `subo dev` right? Or do we need to include it with other commands as well? If so, then which all commands would the flag go with particularly?

**Comment by javorszky** [comment]
#292 merged, closing
