### ISSUE TITLE
Subo should not check for updates when running inside of a Docker container

### ISSUE THREAD

**Issue by jagger27** [suborbital/subo#242]
It appears that the root certs in our Docker images are outdated, producing this error:

```
ℹ️  failed to getLatestVersion: failed to fetch latest subo release: Get "https://api.github.com/repos/suborbital/subo/releases/latest": x509: certificate signed by unknown authority
```

Subo doesn't need to check for updates within Docker anyway, so there should be a build flag or runtime flag to disable that feature.

**Comment by kritikmodi** [comment]
So if the user runs subo with Docker, latest version shouldn't be checked? It should be checked only if they run subo with the `--native` flag?
