### ISSUE TITLE
Enable JavaScript smoketest

### ISSUE THREAD

**Issue by ramonh** [suborbital/subo#251]
According to the [smoketest script](https://github.com/suborbital/subo/blob/main/scripts/smoketest.sh#L34), we should uncomment the JavaScript smoketest if checked in.

If I understood correctly, this is already done, and can be activated? 

Happy to open a PR!

**Comment by ospencer** [comment]
@ramonh This looks like it's done; am I able to close this?

**Comment by ramonh** [comment]
Yes please! Thank you
