### ISSUE TITLE
failed to Run subo dev

### ISSUE THREAD

**Issue by xtuc** [suborbital/subo#40]
I just followed https://atmo.suborbital.dev/getstarted and created an empty project.

When running `subo dev` I see the following:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "chdir to cwd (\"/home/atmo\") set in config.json failed: permission denied": unknown.
time="2021-03-07T13:57:15Z" level=error msg="error waiting for container: context canceled"
Error: 🚫 failed to run dev server: failed to Run command: exit status 126
Usage:
  subo dev [flags]

Flags:
  -h, --help          help for dev
      --port string   set the port that Atmo serves on (default "8080")
```

In the container configuration:
```
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/home/sven/.../important-api",
                "Destination": "/home/atmo",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
```

and my current directory:
```
total 8.0K
-rwxrwxr-x 1 sven sven  384 Mar  7 13:55 Directive.yaml
drwxr-xr-x 3 sven sven 4.0K Mar  7 13:55 helloworld
```

**Comment by xtuc** [comment]
After changing the permissions of the folder, I got it running. Couldn't the CLI fix them for me?

**Comment by cohix** [comment]
@xtuc thanks for filing! Which OS are you running this on? I can't reproduce on macOS Catalina or Big Sur. Could be Linux behaviour?

**Comment by xtuc** [comment]
I'm running Ubuntu, I suppose it's a platform specific issue. After a chmod is works fine, I think we can close this issue if it's only me having it.

**Comment by cohix** [comment]
@xtuc I'd like to detect and auto-fix or give an intelligent error in this case, so let's leave it open! For my own testing, could you tell me the exact `chmod` command you used to fix?

**Comment by xtuc** [comment]
I used `chmod` with 777 but there's probably better permissions.

**Comment by cohix** [comment]
Great, thanks.

**Comment by cohix** [comment]
@xtuc https://github.com/suborbital/subo/pull/43 will cause subo to create projects with `777`, I think that will do the trick (tested on my Raspberry Pi, where I was able to reproduce your issue)
