### ISSUE TITLE
sudo build fails and exits with 0

### ISSUE THREAD

**Issue by xtuc** [suborbital/subo#42]
I noticed that when I run `subo build . --bundle` and it fails to compile, it exits with 0.

More information:
```
...
error: build failed
🚫 failed to doBuild for helloworld: failed to RunInDir: failed to Run command: exit status 101
✅ DONE: helloworld was built -> /home/sven/.../important-api/helloworld/helloworld.wasm
✅ DONE: bundle was created -> runnables.wasm.zip

$ echo $?
0
```

**Comment by cohix** [comment]
@xtuc https://github.com/suborbital/subo/pull/43 will resolve this issue, subo is also running inside the builder images, and for some reason I previously made the decision to only return the error when bundling (which the subo **inside** the container was not), thus making the subo running the container think the build had succeeded. That's some subo-in-subo strangeness.
