### ISSUE TITLE
TinyGo Builder

### ISSUE THREAD

**Issue by cohix** [suborbital/subo#6]
Once Reactr supports TinyGo, Subo should gain the ability to build a Runnable written in Go.

**Comment by gedw99** [comment]
suggest adding to the examples in atmo to show devs how to use tinygo with the system.

**Comment by cohix** [comment]
> suggest adding to the examples in atmo to show devs how to use tinygo with the system.

I think this issues is unclear (I'll update the description)... it's not yet possible to use TinyGo, this issue and the linked Reactr issue are meant to signify that support needs to be added 🙂

**Comment by gedw99** [comment]
@cohix 

Should the title be "support wasm guests using tinygo, so that golang devs can write logic in golang, and run it inside the wasm host. " ?
