### ISSUE TITLE
Can't kill atmo container with CTRL + C

### ISSUE THREAD

**Issue by calebschoepp** [suborbital/subo#61]
Steps to reproduce:

```bash
# Build a project
subo create project test

# Build the project docker image
subo build --docker

# Run the image
docker run com.surborbital.test:v0.0.1

# Try and fail to exit the container with CTRL + C
^C
```

Currently the `Dockerfile` is using the shell form for the `ENTRYPOINT` instead of the exec form ([docs](https://docs.docker.com/engine/reference/builder/#entrypoint)). This means the SIGINT get's picked up by the shell running Atmo and not by Atmo itself ([more on this](https://forums.docker.com/t/docker-run-cannot-be-killed-with-ctrl-c/13108)). If we switch to using the exec form then this issue will be resolved.

Happy to write up a PR for this.

**Comment by cohix** [comment]
Interesting. I know that `subo dev` doesn't have this problem, so the main `Atmo` Dockerfile and the one in the Subo template project must be slightly different. Please feel free to take this on!

**Comment by calebschoepp** [comment]
@cohix On it!
