### ISSUE TITLE
Make integration

### ISSUE THREAD

**Issue by cohix** [suborbital/subo#63]
Developers should be able to configure `subo` to execute Make targets as part of a build. This would allow for things like building static sites before creating a bundle.

For example, if I run `subo build . --make app`, I'd want `subo` to run `make app` before starting the actual build.

**Comment by sangTroo** [comment]
HI, I'm taking this one

**Comment by samderlust** [comment]
Hi, I'm working on this

**Comment by cohix** [comment]
This was completed by @samderlust !
