### ISSUE TITLE
Dead `builders` link in the README

### ISSUE THREAD

**Issue by FanaHOVA** [suborbital/subo#76]
The `builders` folder link in the README is broken (https://github.com/suborbital/subo/blob/main/builders). Is it supposed to point to https://github.com/suborbital/subo/tree/main/builder/docker instead? I can update the README, just making sure that's the correct one!

**Comment by cohix** [comment]
@FanaHOVA yes, that directory was just recently moved and looks like I didn't update the README. Feel free to make that change :)

**Comment by FanaHOVA** [comment]
Great, see #78
